#include "../LoyMath/Float16.h"
#include <limits>
#include <iostream>

using namespace LoyMath;
using namespace std;

void testFp16()
{
    float f32_zero_pos                =  1.4012984643e-46f;
    float f32_zero_neg                = -1.4012984643e-46f;
    float f32_subnormal_small_pos     =  1.4012984643e-45f;
    float f32_subnormal_small_neg     = -1.4012984643e-45f;
    float f32_subnormal_large_pos     =  1.1754942107e-38f;
    float f32_subnormal_large_neg     = -1.1754942107e-38f;
    float f32_normal_small_pos        =  1.1754943508e-38f;
    float f32_normal_small_neg        = -1.1754943508e-38f;
    float f32_to_zero_pos             =  0.000000020000000f;
    float f32_to_zero_neg             = -0.000000020000000f;
    float f32_rto_subnormal_small_pos =  0.000000059604641f;
    float f32_rto_subnormal_small_neg = -0.000000059604641f;
    float f32_to_subnormal_small_pos  =  0.000000059604645f;
    float f32_to_subnormal_small_neg  = -0.000000059604645f;
    float f32_to_subnormal_large_pos  =  0.000060975552f;
    float f32_to_subnormal_large_neg  = -0.000060975552f;
    float f32_rto_normal_small_pos    =  0.00006103515400f;
    float f32_rto_normal_small_neg    = -0.00006103515400f;
    float f32_to_normal_small_pos     =  0.00006103515625f;
    float f32_to_normal_small_neg     = -0.00006103515625f;
    float f32_to_normal_less_one_pos  =  0.99951172f;
    float f32_to_normal_less_one_neg  = -0.99951172f;
    float f32_normal_less_one_pos     =  0.999999940395355225f;
    float f32_normal_less_one_neg     = -0.999999940395355225f;
    float f32_one_pos                 =  1.0f;
    float f32_one_neg                 = -1.0f;
    float f32_normal_more_one_pos     =  1.00000011920928955f;
    float f32_normal_more_one_neg     = -1.00000011920928955f;
    float f32_to_normal_more_one_pos  =  1.00097656f;
    float f32_to_normal_more_one_neg  = -1.00097656f;
    float f32_normal_pos              =  3.1415926536e000f;
    float f32_normal_neg              = -3.1415926536e000f;
    float f32_to_normal_large_pos     =  65504.0f;
    float f32_to_normal_large_neg     = -65504.0f;
    float f32_rto_inf_pos             =  65535.0f;
    float f32_rto_inf_neg             = -65535.0f;
    float f32_to_inf_pos              =  65536.0f;
    float f32_to_inf_neg              = -65536.0f;
    float f32_normal_large_pos        =  3.4028234664e+38f;
    float f32_normal_large_neg        = -3.4028234664e+38f;
    float f32_inf_pos                 =  numeric_limits<float>::infinity();
    float f32_inf_neg                 = -numeric_limits<float>::infinity();
    float f32_snan_pos                =  numeric_limits<float>::signaling_NaN();
    float f32_snan_neg                = -numeric_limits<float>::signaling_NaN();
    float f32_qnan_pos                =  numeric_limits<float>::quiet_NaN();
    float f32_qnan_neg                = -numeric_limits<float>::quiet_NaN();
    float f32_indet                   ;    // gcc does not support indetermin and it's the same as qnan_nag.
    *(uint32_t *)&f32_indet = (1UL << 31) | (255UL << 23) | (1UL << 22);

    float16 f16_zero_pos               (f32_zero_pos               ); 
    float16 f16_zero_neg               (f32_zero_neg               ); 
    float16 f16_subnormal_small_pos    (f32_subnormal_small_pos    ); 
    float16 f16_subnormal_small_neg    (f32_subnormal_small_neg    ); 
    float16 f16_subnormal_large_pos    (f32_subnormal_large_pos    ); 
    float16 f16_subnormal_large_neg    (f32_subnormal_large_neg    ); 
    float16 f16_normal_small_pos       (f32_normal_small_pos       ); 
    float16 f16_normal_small_neg       (f32_normal_small_neg       ); 
    float16 f16_to_zero_pos            (f32_to_zero_pos            ); 
    float16 f16_to_zero_neg            (f32_to_zero_neg            ); 
    float16 f16_rto_subnormal_small_pos(f32_rto_subnormal_small_pos);
    float16 f16_rto_subnormal_small_neg(f32_rto_subnormal_small_neg);
    float16 f16_to_subnormal_small_pos (f32_to_subnormal_small_pos ); 
    float16 f16_to_subnormal_small_neg (f32_to_subnormal_small_neg ); 
    float16 f16_to_subnormal_large_pos (f32_to_subnormal_large_pos ); 
    float16 f16_to_subnormal_large_neg (f32_to_subnormal_large_neg );
    float16 f16_rto_normal_small_pos   (f32_rto_normal_small_pos   );
    float16 f16_rto_normal_small_neg   (f32_rto_normal_small_neg   ); 
    float16 f16_to_normal_small_pos    (f32_to_normal_small_pos    ); 
    float16 f16_to_normal_small_neg    (f32_to_normal_small_neg    ); 
    float16 f16_to_normal_less_one_pos (f32_to_normal_less_one_pos ); 
    float16 f16_to_normal_less_one_neg (f32_to_normal_less_one_neg ); 
    float16 f16_normal_less_one_pos    (f32_normal_less_one_pos    ); 
    float16 f16_normal_less_one_neg    (f32_normal_less_one_neg    ); 
    float16 f16_one_pos                (f32_one_pos                ); 
    float16 f16_one_neg                (f32_one_neg                ); 
    float16 f16_normal_more_one_pos    (f32_normal_more_one_pos    ); 
    float16 f16_normal_more_one_neg    (f32_normal_more_one_neg    ); 
    float16 f16_to_normal_more_one_pos (f32_to_normal_more_one_pos ); 
    float16 f16_to_normal_more_one_neg (f32_to_normal_more_one_neg ); 
    float16 f16_normal_pos             (f32_normal_pos             ); 
    float16 f16_normal_neg             (f32_normal_neg             ); 
    float16 f16_to_normal_large_pos    (f32_to_normal_large_pos    ); 
    float16 f16_to_normal_large_neg    (f32_to_normal_large_neg    ); 
    float16 f16_rto_inf_pos            (f32_rto_inf_pos            ); 
    float16 f16_rto_inf_neg            (f32_rto_inf_neg            ); 
    float16 f16_to_inf_pos             (f32_to_inf_pos             ); 
    float16 f16_to_inf_neg             (f32_to_inf_neg             ); 
    float16 f16_normal_large_pos       (f32_normal_large_pos       ); 
    float16 f16_normal_large_neg       (f32_normal_large_neg       ); 
    float16 f16_inf_pos                (f32_inf_pos                ); 
    float16 f16_inf_neg                (f32_inf_neg                ); 
    float16 f16_snan_pos               (f32_snan_pos               ); 
    float16 f16_snan_neg               (f32_snan_neg               ); 
    float16 f16_qnan_pos               (f32_qnan_pos               ); 
    float16 f16_qnan_neg               (f32_qnan_neg               ); 
    float16 f16_indet                  (f32_indet                  );

    // cout << f32_zero_pos                << ": " << f16_zero_pos                << ", " << f16_zero_pos               .to_base() << ", " << f16_zero_pos               .to_base2() << endl;
    // cout << f32_zero_neg                << ": " << f16_zero_neg                << ", " << f16_zero_neg               .to_base() << ", " << f16_zero_neg               .to_base2() << endl;
    // cout << f32_subnormal_small_pos     << ": " << f16_subnormal_small_pos     << ", " << f16_subnormal_small_pos    .to_base() << ", " << f16_subnormal_small_pos    .to_base2() << endl;
    // cout << f32_subnormal_small_neg     << ": " << f16_subnormal_small_neg     << ", " << f16_subnormal_small_neg    .to_base() << ", " << f16_subnormal_small_neg    .to_base2() << endl;
    // cout << f32_subnormal_large_pos     << ": " << f16_subnormal_large_pos     << ", " << f16_subnormal_large_pos    .to_base() << ", " << f16_subnormal_large_pos    .to_base2() << endl;
    // cout << f32_subnormal_large_neg     << ": " << f16_subnormal_large_neg     << ", " << f16_subnormal_large_neg    .to_base() << ", " << f16_subnormal_large_neg    .to_base2() << endl;
    // cout << f32_normal_small_pos        << ": " << f16_normal_small_pos        << ", " << f16_normal_small_pos       .to_base() << ", " << f16_normal_small_pos       .to_base2() << endl;
    // cout << f32_normal_small_neg        << ": " << f16_normal_small_neg        << ", " << f16_normal_small_neg       .to_base() << ", " << f16_normal_small_neg       .to_base2() << endl;
    // cout << f32_to_zero_pos             << ": " << f16_to_zero_pos             << ", " << f16_to_zero_pos            .to_base() << ", " << f16_to_zero_pos            .to_base2() << endl;
    // cout << f32_to_zero_neg             << ": " << f16_to_zero_neg             << ", " << f16_to_zero_neg            .to_base() << ", " << f16_to_zero_neg            .to_base2() << endl;
    // cout << f32_rto_subnormal_small_pos << ": " << f16_rto_subnormal_small_pos << ", " << f16_rto_subnormal_small_pos.to_base() << ", " << f16_rto_subnormal_small_pos.to_base2() << endl;
    // cout << f32_rto_subnormal_small_neg << ": " << f16_rto_subnormal_small_neg << ", " << f16_rto_subnormal_small_neg.to_base() << ", " << f16_rto_subnormal_small_neg.to_base2() << endl;
    // cout << f32_to_subnormal_small_pos  << ": " << f16_to_subnormal_small_pos  << ", " << f16_to_subnormal_small_pos .to_base() << ", " << f16_to_subnormal_small_pos .to_base2() << endl;
    // cout << f32_to_subnormal_small_neg  << ": " << f16_to_subnormal_small_neg  << ", " << f16_to_subnormal_small_neg .to_base() << ", " << f16_to_subnormal_small_neg .to_base2() << endl;
    // cout << f32_to_subnormal_large_pos  << ": " << f16_to_subnormal_large_pos  << ", " << f16_to_subnormal_large_pos .to_base() << ", " << f16_to_subnormal_large_pos .to_base2() << endl;
    // cout << f32_to_subnormal_large_neg  << ": " << f16_to_subnormal_large_neg  << ", " << f16_to_subnormal_large_neg .to_base() << ", " << f16_to_subnormal_large_neg .to_base2() << endl;
    // cout << f32_rto_normal_small_pos    << ": " << f16_rto_normal_small_pos    << ", " << f16_rto_normal_small_pos   .to_base() << ", " << f16_rto_normal_small_pos   .to_base2() << endl;
    // cout << f32_rto_normal_small_neg    << ": " << f16_rto_normal_small_neg    << ", " << f16_rto_normal_small_neg   .to_base() << ", " << f16_rto_normal_small_neg   .to_base2() << endl;
    // cout << f32_to_normal_small_pos     << ": " << f16_to_normal_small_pos     << ", " << f16_to_normal_small_pos    .to_base() << ", " << f16_to_normal_small_pos    .to_base2() << endl;
    // cout << f32_to_normal_small_neg     << ": " << f16_to_normal_small_neg     << ", " << f16_to_normal_small_neg    .to_base() << ", " << f16_to_normal_small_neg    .to_base2() << endl;
    // cout << f32_to_normal_less_one_pos  << ": " << f16_to_normal_less_one_pos  << ", " << f16_to_normal_less_one_pos .to_base() << ", " << f16_to_normal_less_one_pos .to_base2() << endl;
    // cout << f32_to_normal_less_one_neg  << ": " << f16_to_normal_less_one_neg  << ", " << f16_to_normal_less_one_neg .to_base() << ", " << f16_to_normal_less_one_neg .to_base2() << endl;
    // cout << f32_normal_less_one_pos     << ": " << f16_normal_less_one_pos     << ", " << f16_normal_less_one_pos    .to_base() << ", " << f16_normal_less_one_pos    .to_base2() << endl;
    // cout << f32_normal_less_one_neg     << ": " << f16_normal_less_one_neg     << ", " << f16_normal_less_one_neg    .to_base() << ", " << f16_normal_less_one_neg    .to_base2() << endl;
    // cout << f32_one_pos                 << ": " << f16_one_pos                 << ", " << f16_one_pos                .to_base() << ", " << f16_one_pos                .to_base2() << endl;
    // cout << f32_one_neg                 << ": " << f16_one_neg                 << ", " << f16_one_neg                .to_base() << ", " << f16_one_neg                .to_base2() << endl;
    // cout << f32_normal_more_one_pos     << ": " << f16_normal_more_one_pos     << ", " << f16_normal_more_one_pos    .to_base() << ", " << f16_normal_more_one_pos    .to_base2() << endl;
    // cout << f32_normal_more_one_neg     << ": " << f16_normal_more_one_neg     << ", " << f16_normal_more_one_neg    .to_base() << ", " << f16_normal_more_one_neg    .to_base2() << endl;
    // cout << f32_to_normal_more_one_pos  << ": " << f16_to_normal_more_one_pos  << ", " << f16_to_normal_more_one_pos .to_base() << ", " << f16_to_normal_more_one_pos .to_base2() << endl;
    // cout << f32_to_normal_more_one_neg  << ": " << f16_to_normal_more_one_neg  << ", " << f16_to_normal_more_one_neg .to_base() << ", " << f16_to_normal_more_one_neg .to_base2() << endl;
    // cout << f32_normal_pos              << ": " << f16_normal_pos              << ", " << f16_normal_pos             .to_base() << ", " << f16_normal_pos             .to_base2() << endl;
    // cout << f32_normal_neg              << ": " << f16_normal_neg              << ", " << f16_normal_neg             .to_base() << ", " << f16_normal_neg             .to_base2() << endl;
    // cout << f32_to_normal_large_pos     << ": " << f16_to_normal_large_pos     << ", " << f16_to_normal_large_pos    .to_base() << ", " << f16_to_normal_large_pos    .to_base2() << endl;
    // cout << f32_to_normal_large_neg     << ": " << f16_to_normal_large_neg     << ", " << f16_to_normal_large_neg    .to_base() << ", " << f16_to_normal_large_neg    .to_base2() << endl;
    // cout << f32_rto_inf_pos             << ": " << f16_rto_inf_pos             << ", " << f16_rto_inf_pos            .to_base() << ", " << f16_rto_inf_pos            .to_base2() << endl;
    // cout << f32_rto_inf_neg             << ": " << f16_rto_inf_neg             << ", " << f16_rto_inf_neg            .to_base() << ", " << f16_rto_inf_neg            .to_base2() << endl;
    // cout << f32_to_inf_pos              << ": " << f16_to_inf_pos              << ", " << f16_to_inf_pos             .to_base() << ", " << f16_to_inf_pos             .to_base2() << endl;
    // cout << f32_to_inf_neg              << ": " << f16_to_inf_neg              << ", " << f16_to_inf_neg             .to_base() << ", " << f16_to_inf_neg             .to_base2() << endl;
    // cout << f32_normal_large_pos        << ": " << f16_normal_large_pos        << ", " << f16_normal_large_pos       .to_base() << ", " << f16_normal_large_pos       .to_base2() << endl;
    // cout << f32_normal_large_neg        << ": " << f16_normal_large_neg        << ", " << f16_normal_large_neg       .to_base() << ", " << f16_normal_large_neg       .to_base2() << endl;
    // cout << f32_inf_pos                 << ": " << f16_inf_pos                 << ", " << f16_inf_pos                .to_base() << ", " << f16_inf_pos                .to_base2() << endl;
    // cout << f32_inf_neg                 << ": " << f16_inf_neg                 << ", " << f16_inf_neg                .to_base() << ", " << f16_inf_neg                .to_base2() << endl;
    // cout << f32_snan_pos                << ": " << f16_snan_pos                << ", " << f16_snan_pos               .to_base() << ", " << f16_snan_pos               .to_base2() << endl;
    // cout << f32_snan_neg                << ": " << f16_snan_neg                << ", " << f16_snan_neg               .to_base() << ", " << f16_snan_neg               .to_base2() << endl;
    // cout << f32_qnan_pos                << ": " << f16_qnan_pos                << ", " << f16_qnan_pos               .to_base() << ", " << f16_qnan_pos               .to_base2() << endl;
    // cout << f32_qnan_neg                << ": " << f16_qnan_neg                << ", " << f16_qnan_neg               .to_base() << ", " << f16_qnan_neg               .to_base2() << endl;
    // cout << f32_indet                   << ": " << f16_indet                   << ", " << f16_indet                  .to_base() << ", " << f16_indet                  .to_base2() << endl;

    printf("zero_pos               : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_zero_pos               , (float)f16_zero_pos               , f16_zero_pos               .to_base(), f16_zero_pos               .to_base2());
    printf("zero_neg               : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_zero_neg               , (float)f16_zero_neg               , f16_zero_neg               .to_base(), f16_zero_neg               .to_base2());
    printf("subnormal_small_pos    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_subnormal_small_pos    , (float)f16_subnormal_small_pos    , f16_subnormal_small_pos    .to_base(), f16_subnormal_small_pos    .to_base2());
    printf("subnormal_small_neg    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_subnormal_small_neg    , (float)f16_subnormal_small_neg    , f16_subnormal_small_neg    .to_base(), f16_subnormal_small_neg    .to_base2());
    printf("subnormal_large_pos    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_subnormal_large_pos    , (float)f16_subnormal_large_pos    , f16_subnormal_large_pos    .to_base(), f16_subnormal_large_pos    .to_base2());
    printf("subnormal_large_neg    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_subnormal_large_neg    , (float)f16_subnormal_large_neg    , f16_subnormal_large_neg    .to_base(), f16_subnormal_large_neg    .to_base2());
    printf("normal_small_pos       : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_small_pos       , (float)f16_normal_small_pos       , f16_normal_small_pos       .to_base(), f16_normal_small_pos       .to_base2());
    printf("normal_small_neg       : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_small_neg       , (float)f16_normal_small_neg       , f16_normal_small_neg       .to_base(), f16_normal_small_neg       .to_base2());
    printf("to_zero_pos            : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_zero_pos            , (float)f16_to_zero_pos            , f16_to_zero_pos            .to_base(), f16_to_zero_pos            .to_base2());
    printf("to_zero_neg            : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_zero_neg            , (float)f16_to_zero_neg            , f16_to_zero_neg            .to_base(), f16_to_zero_neg            .to_base2());
    printf("rto_subnormal_small_pos: fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_rto_subnormal_small_pos, (float)f16_rto_subnormal_small_pos, f16_rto_subnormal_small_pos.to_base(), f16_rto_subnormal_small_pos.to_base2());
    printf("rto_subnormal_small_neg: fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_rto_subnormal_small_neg, (float)f16_rto_subnormal_small_neg, f16_rto_subnormal_small_neg.to_base(), f16_rto_subnormal_small_neg.to_base2());
    printf("to_subnormal_small_pos : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_subnormal_small_pos , (float)f16_to_subnormal_small_pos , f16_to_subnormal_small_pos .to_base(), f16_to_subnormal_small_pos .to_base2());
    printf("to_subnormal_small_neg : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_subnormal_small_neg , (float)f16_to_subnormal_small_neg , f16_to_subnormal_small_neg .to_base(), f16_to_subnormal_small_neg .to_base2());
    printf("to_subnormal_large_pos : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_subnormal_large_pos , (float)f16_to_subnormal_large_pos , f16_to_subnormal_large_pos .to_base(), f16_to_subnormal_large_pos .to_base2());
    printf("to_subnormal_large_neg : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_subnormal_large_neg , (float)f16_to_subnormal_large_neg , f16_to_subnormal_large_neg .to_base(), f16_to_subnormal_large_neg .to_base2());
    printf("rto_normal_small_pos   : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_rto_normal_small_pos   , (float)f16_rto_normal_small_pos   , f16_rto_normal_small_pos   .to_base(), f16_rto_normal_small_pos   .to_base2());
    printf("rto_normal_small_neg   : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_rto_normal_small_neg   , (float)f16_rto_normal_small_neg   , f16_rto_normal_small_neg   .to_base(), f16_rto_normal_small_neg   .to_base2());
    printf("to_normal_small_pos    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_normal_small_pos    , (float)f16_to_normal_small_pos    , f16_to_normal_small_pos    .to_base(), f16_to_normal_small_pos    .to_base2());
    printf("to_normal_small_neg    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_normal_small_neg    , (float)f16_to_normal_small_neg    , f16_to_normal_small_neg    .to_base(), f16_to_normal_small_neg    .to_base2());
    printf("to_normal_less_one_pos : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_normal_less_one_pos , (float)f16_to_normal_less_one_pos , f16_to_normal_less_one_pos .to_base(), f16_to_normal_less_one_pos .to_base2());
    printf("to_normal_less_one_neg : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_normal_less_one_neg , (float)f16_to_normal_less_one_neg , f16_to_normal_less_one_neg .to_base(), f16_to_normal_less_one_neg .to_base2());
    printf("normal_less_one_pos    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_less_one_pos    , (float)f16_normal_less_one_pos    , f16_normal_less_one_pos    .to_base(), f16_normal_less_one_pos    .to_base2());
    printf("normal_less_one_neg    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_less_one_neg    , (float)f16_normal_less_one_neg    , f16_normal_less_one_neg    .to_base(), f16_normal_less_one_neg    .to_base2());
    printf("one_pos                : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_one_pos                , (float)f16_one_pos                , f16_one_pos                .to_base(), f16_one_pos                .to_base2());
    printf("one_neg                : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_one_neg                , (float)f16_one_neg                , f16_one_neg                .to_base(), f16_one_neg                .to_base2());
    printf("normal_more_one_pos    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_more_one_pos    , (float)f16_normal_more_one_pos    , f16_normal_more_one_pos    .to_base(), f16_normal_more_one_pos    .to_base2());
    printf("normal_more_one_neg    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_more_one_neg    , (float)f16_normal_more_one_neg    , f16_normal_more_one_neg    .to_base(), f16_normal_more_one_neg    .to_base2());
    printf("to_normal_more_one_pos : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_normal_more_one_pos , (float)f16_to_normal_more_one_pos , f16_to_normal_more_one_pos .to_base(), f16_to_normal_more_one_pos .to_base2());
    printf("to_normal_more_one_neg : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_normal_more_one_neg , (float)f16_to_normal_more_one_neg , f16_to_normal_more_one_neg .to_base(), f16_to_normal_more_one_neg .to_base2());
    printf("normal_pos             : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_pos             , (float)f16_normal_pos             , f16_normal_pos             .to_base(), f16_normal_pos             .to_base2());
    printf("normal_neg             : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_neg             , (float)f16_normal_neg             , f16_normal_neg             .to_base(), f16_normal_neg             .to_base2());
    printf("to_normal_large_pos    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_normal_large_pos    , (float)f16_to_normal_large_pos    , f16_to_normal_large_pos    .to_base(), f16_to_normal_large_pos    .to_base2());
    printf("to_normal_large_neg    : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_normal_large_neg    , (float)f16_to_normal_large_neg    , f16_to_normal_large_neg    .to_base(), f16_to_normal_large_neg    .to_base2());
    printf("rto_inf_pos            : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_rto_inf_pos            , (float)f16_rto_inf_pos            , f16_rto_inf_pos            .to_base(), f16_rto_inf_pos            .to_base2());
    printf("rto_inf_neg            : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_rto_inf_neg            , (float)f16_rto_inf_neg            , f16_rto_inf_neg            .to_base(), f16_rto_inf_neg            .to_base2());
    printf("to_inf_pos             : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_inf_pos             , (float)f16_to_inf_pos             , f16_to_inf_pos             .to_base(), f16_to_inf_pos             .to_base2());
    printf("to_inf_neg             : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_to_inf_neg             , (float)f16_to_inf_neg             , f16_to_inf_neg             .to_base(), f16_to_inf_neg             .to_base2());
    printf("normal_large_pos       : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_large_pos       , (float)f16_normal_large_pos       , f16_normal_large_pos       .to_base(), f16_normal_large_pos       .to_base2());
    printf("normal_large_neg       : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_normal_large_neg       , (float)f16_normal_large_neg       , f16_normal_large_neg       .to_base(), f16_normal_large_neg       .to_base2());
    printf("inf_pos                : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_inf_pos                , (float)f16_inf_pos                , f16_inf_pos                .to_base(), f16_inf_pos                .to_base2());
    printf("inf_neg                : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_inf_neg                , (float)f16_inf_neg                , f16_inf_neg                .to_base(), f16_inf_neg                .to_base2());
    printf("snan_pos               : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_snan_pos               , (float)f16_snan_pos               , f16_snan_pos               .to_base(), f16_snan_pos               .to_base2());
    printf("snan_neg               : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_snan_neg               , (float)f16_snan_neg               , f16_snan_neg               .to_base(), f16_snan_neg               .to_base2());
    printf("qnan_pos               : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_qnan_pos               , (float)f16_qnan_pos               , f16_qnan_pos               .to_base(), f16_qnan_pos               .to_base2());
    printf("qnan_neg               : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_qnan_neg               , (float)f16_qnan_neg               , f16_qnan_neg               .to_base(), f16_qnan_neg               .to_base2());
    printf("indet                  : fp32: %12g, fp16(type cast): %12g, fp16(bits convert): %12g, fp16(math convert): %12g.\r\n", f32_indet                  , (float)f16_indet                  , f16_indet                  .to_base(), f16_indet                  .to_base2());


	float16 a = 1.12f;
	float16 b = 3.3f;
	b -= 1.0f;
	b /= 2.3f;
	b += 1.0f;
	b *= 2.5f;
	cout << a << endl;
	cout << b << endl;
	cout << a + b << endl;
	cout << a - b << endl;
	cout << a * b << endl;
	cout << a / b << endl;
}

